# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fewshot/configs/protonet_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fewshot/configs/protonet_config.proto',
  package='fewshot.configs',
  serialized_pb=_b('\n%fewshot/configs/protonet_config.proto\x12\x0f\x66\x65wshot.configs\"\xcb\x01\n\x0eProtonetConfig\x12\x1d\n\nsimilarity\x18\x01 \x01(\t:\teuclidean\x12\x10\n\x08\x63osine_a\x18\x02 \x01(\x08\x12\x12\n\ncosine_tau\x18\x03 \x01(\x08\x12\x16\n\x0e\x63osine_softmax\x18\x04 \x01(\x08\x12\x1a\n\x12\x63osine_softmax_tau\x18\x05 \x01(\x08\x12\x18\n\x10\x63osine_attention\x18\x06 \x01(\x08\x12\x12\n\nprotos_phi\x18\x07 \x01(\x08\x12\x12\n\nreinit_tau\x18\x08 \x01(\x08')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROTONETCONFIG = _descriptor.Descriptor(
  name='ProtonetConfig',
  full_name='fewshot.configs.ProtonetConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='similarity', full_name='fewshot.configs.ProtonetConfig.similarity', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("euclidean").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cosine_a', full_name='fewshot.configs.ProtonetConfig.cosine_a', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cosine_tau', full_name='fewshot.configs.ProtonetConfig.cosine_tau', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cosine_softmax', full_name='fewshot.configs.ProtonetConfig.cosine_softmax', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cosine_softmax_tau', full_name='fewshot.configs.ProtonetConfig.cosine_softmax_tau', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cosine_attention', full_name='fewshot.configs.ProtonetConfig.cosine_attention', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='protos_phi', full_name='fewshot.configs.ProtonetConfig.protos_phi', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reinit_tau', full_name='fewshot.configs.ProtonetConfig.reinit_tau', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=262,
)

DESCRIPTOR.message_types_by_name['ProtonetConfig'] = _PROTONETCONFIG

ProtonetConfig = _reflection.GeneratedProtocolMessageType('ProtonetConfig', (_message.Message,), dict(
  DESCRIPTOR = _PROTONETCONFIG,
  __module__ = 'fewshot.configs.protonet_config_pb2'
  # @@protoc_insertion_point(class_scope:fewshot.configs.ProtonetConfig)
  ))
_sym_db.RegisterMessage(ProtonetConfig)


# @@protoc_insertion_point(module_scope)
